# Generated by Django 5.2.1 on 2025-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0003_remove_workplace_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="table",
            field=models.IntegerField(unique=True),
        ),
    ]
