# Generated by Django 5.2.1 on 2025-09-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0004_alter_workplace_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="table",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
