# Generated by Django 5.2.1 on 2025-09-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
    ]
