# Generated by Django 5.2.1 on 2025-09-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_skill_skilllevel_employee_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skilllevel",
            options={
                "verbose_name": "Уровень навыка",
                "verbose_name_plural": "Уровни навыка",
            },
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="skills",
            new_name="skill",
        ),
    ]
