# Generated by Django 5.2.1 on 2025-09-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_rename_skill_employee_skills_employee_workplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="workplace",
        ),
    ]
