# Generated by Django 5.2.1 on 2025-09-06 14:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_employee_workplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
