# Generated by Django 5.2.1 on 2025-09-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_alter_employee_first_name"),
        ("workplaces", "0003_remove_workplace_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="workplace",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workplaces.workplace",
                verbose_name="Рабочее место",
            ),
        ),
    ]
