# Generated by Django 5.2.1 on 2025-09-15 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_alter_employee_gender_alter_employee_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2025, 9, 15, 22, 56, 38, 53517),
                null=True,
                verbose_name="Дата приёма на работу",
            ),
        ),
    ]
