# Generated by Django 5.2.1 on 2025-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_employee_employment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приёма на работу"
            ),
        ),
    ]
