# Generated by Django 5.2.1 on 2025-09-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_alter_employee_employment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True,
                verbose_name="Стаж в днях",
            ),
        ),
    ]
