# Generated by Django 5.2.1 on 2025-09-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0014_employee_employment_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("developer", "разработчик"),
                    ("qa-engineer", "тестировщик"),
                    ("project-manager", "руководитель проекта"),
                    ("prompt engineer", "промпт-инженер"),
                    ("other", "другое"),
                ],
                default="other",
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
