# Generated by Django 5.2.1 on 2025-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0015_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frontend-developer", "фронтенд разработчик"),
                    ("backend-developer", "бэкенд разработчик"),
                    ("qa-engineer", "тестировщик"),
                    ("project-manager", "руководитель проекта"),
                    ("prompt engineer", "промпт-инженер"),
                    ("other", "другое"),
                ],
                default="other",
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
