# Generated by Django 5.2.1 on 2025-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0016_alter_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeimage",
            name="image",
            field=models.ImageField(
                null=True, upload_to="employee_images/", verbose_name="Изображение"
            ),
        ),
    ]
