# Generated by Django 5.2.1 on 2025-09-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_remove_employee_workplace"),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.employee",
            ),
        ),
    ]
