# Generated by Django 5.2.1 on 2025-09-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_workplace_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="employee",
        ),
    ]
