# Generated by Django 5.2.1 on 2025-09-06 05:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_skilllevel_options_and_more"),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="skill",
            new_name="skills",
        ),
        migrations.AddField(
            model_name="employee",
            name="workplace",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workplaces.workplace",
            ),
        ),
        migrations.AlterField(
            model_name="skilllevel",
            name="level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
