# Generated by Django 5.2.1 on 2025-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_skill_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
    ]
